### ISSUE TITLE
Make it possible to know which bundle was used for a preexisting VM

### ISSUE THREAD

**Issue by cfergeau** [code-ready/machine#19]
At the moment, machine.Start() always assume the bundle which is going to be
used is the default one which was used when building the binary/which was
passed through the -b option
This leads to various unwanted behaviours, which I'll detail in another bug.

First step towards fixing that is to be able to know which bundle was used to
create a preexisting vm in `~/.crc/machines/crc/`

**Comment by praveenkumar** [comment]
Fixed by #20
