### ISSUE TITLE
Some tests reference non-existing modules

### ISSUE THREAD

**Issue by cfergeau** [code-ready/machine#28]
`libmachine/host/host_test.go` imports `libmachine/provision`, and `migrate_v0_v1_test.go/filestore_test.go` import `commands/mcndirs`, which both are not present in our fork of `machine`.
I noticed this because of complaints when running `go mod tidy` in the crc repository.



**Comment by praveenkumar** [comment]
@cfergeau we are not running the tests so we should remove `host_test.go` and `filestore_test.go` files from here so `go mod tidy` is not blocked.
